/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_cognito_identity_pool_id": "ap-southeast-1:33bc455c-26e1-4261-b2f8-9708c690a095",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_gAQdcyP3v",
    "aws_user_pools_web_client_id": "1lj6tkjgfspg93rjmu27tga4gn",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://6gxwvqlpibhjzfl6d2drt7pu4i.appsync-api.ap-southeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-southeast-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-t3cwn7ef5rfancabwcu63nno3i"
};


export default awsmobile;
